spring:
  application:
    name: SampleUber

mvf4ms:
  version: 2.2.3
  dependencies:
    - name: dependency1
      dependence:
        - id: pay
          function: pay
          slas:
            - 3
        - id: navigation
          function: navigation
          slas:
            - 3

server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTRY}/eureka
